- name: Create an EC2 webserver instance
  ec2:
    keypair: "{{ ec2_key_name }}"
    region: "{{ vpc_region }}"
    group_id: "{{ ec2_sshable_sg_id }}"
    instance_type: "{{ ec2_db_instance_type }}"
    image: "{{ ec2_db_ami_id }}"
    vpc_subnet_id: "{{ public_subnet_01_id }}"
    assign_public_ip: yes
    wait: True
    wait_timeout: 300
    instance_tags:
      Env: "{{ env }}"
      Name: "{{ project_name }}_web"
      Role: "database"
    count_tag:
      Env: "{{ env }}"
      Name: "{{ project_name }}"
      Role: "database"
    exact_count: "{{ ec2_db_instance_count }}"
  register: ec2

- name: Add new instances to host group
  add_host:
    name: "{{ item.public_dns_name }}"
    groups: "database"
    ec2_id: "{{ item.id }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up on EC2 Instance(s)
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
