---
- name: install python3-pip
yum:
      name: python3-pip
      state: present 
      
- name: install maria db
  yum:
      name: mariadb-server
      state: present
- name: start the service
  service:
      name: mariadb
      state: started
- name: install
  command: "pip3 install  pymysql"
- name: create the db
  mysql_db:
      name: wordpress
      state: present
- name: create the db user
  mysql_user:
      name: wordpress
      password: wordpress
      priv: '*.*:ALL'
      state: present
