- name: Creating an EC2 Security Groups inside the Mentioned VPC
  ec2_group:
    name: "sshable-sg"
    description: "can connect via ssh"
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc_id }}"
    state: present
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  register: aws_sg